name: flutter_esc_pos_network
description: The library allows printing receipts using ESC/POS commands using thermal Wi-Fi/Ethernet printer.
version: 1.0.2
homepage: https://github.com/mjafartp/flutter_esc_pos_network

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_esc_pos_utils: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
